/**
 * CI/CD Workflow Template Definitions
 * Contains inline YAML templates for GitHub Actions and GitLab CI
 */

// ============ Type Definitions ============

export type CIPlatform = 'github' | 'gitlab';
export type TemplateType = 'pr-review' | 'code-check' | 'feature-implement';

export interface CITemplate {
  id: string;
  name: string;
  platform: CIPlatform;
  type: TemplateType;
  description: string;
  outputPath: string;
  content: string;
}

// ============ GitHub Actions Templates ============

/**
 * GitHub Actions - PR Review Template
 * Triggers on pull_request events to review changes with AI
 */
const githubPrReviewTemplate: CITemplate = {
  id: 'github-pr-review',
  name: 'GitHub Actions - PR Review',
  platform: 'github',
  type: 'pr-review',
  description: 'Automatically review pull requests using SAP AI Core and post feedback as PR comments',
  outputPath: '.github/workflows/ai-pr-review.yml',
  content: `# AI-Powered PR Review Workflow
# This workflow uses Alexi to review pull requests
#
# Setup:
# 1. Add SAP AI Core credentials as repository secrets:
#    - SAP_AICORE_SERVICE_KEY: Your SAP AI Core service key JSON
#    OR for proxy mode:
#    - SAP_PROXY_BASE_URL: URL to your SAP proxy server
#    - SAP_PROXY_API_KEY: API key for proxy authentication (if required)
#
# 2. Ensure the workflow has permission to comment on PRs:
#    Settings > Actions > General > Workflow permissions > Read and write permissions

name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for diff analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Alexi
        run: npm install -g alexi
      
      - name: Get PR diff
        id: diff
        run: |
          # Get the diff between base and head
          git diff origin/\${{ github.base_ref }}...HEAD > pr_diff.txt
          echo "diff_file=pr_diff.txt" >> $GITHUB_OUTPUT
      
      - name: Run AI Review
        id: review
        env:
          AICORE_SERVICE_KEY: \${{ secrets.SAP_AICORE_SERVICE_KEY }}
          SAP_PROXY_BASE_URL: \${{ secrets.SAP_PROXY_BASE_URL }}
          SAP_PROXY_API_KEY: \${{ secrets.SAP_PROXY_API_KEY }}
        run: |
          # Create review prompt
          cat << 'PROMPT' > review_prompt.txt
          Review the following code changes from a pull request.
          
          Provide feedback on:
          1. Code quality and best practices
          2. Potential bugs or issues
          3. Security concerns
          4. Performance implications
          5. Suggestions for improvement
          
          Be constructive and specific. Reference line numbers when applicable.
          Format your response in markdown.
          
          PR Title: \${{ github.event.pull_request.title }}
          PR Description: \${{ github.event.pull_request.body }}
          
          Code Changes:
          PROMPT
          
          cat pr_diff.txt >> review_prompt.txt
          
          # Run alexi and capture output
          alexi --prompt "$(cat review_prompt.txt)" --output review_output.md --non-interactive || true
          
          # Check if review was generated
          if [ -f review_output.md ]; then
            echo "review_generated=true" >> $GITHUB_OUTPUT
          else
            echo "review_generated=false" >> $GITHUB_OUTPUT
            echo "AI review could not be generated" > review_output.md
          fi
      
      - name: Post Review Comment
        if: steps.review.outputs.review_generated == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review_output.md', 'utf8');
            
            const body = \`## AI Code Review
            
            \${review}
            
            ---
            *This review was generated by Alexi*
            \`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
`,
};

/**
 * GitHub Actions - Code Check Template
 * Triggers on push to main/master for code quality analysis
 */
const githubCodeCheckTemplate: CITemplate = {
  id: 'github-code-check',
  name: 'GitHub Actions - Code Check',
  platform: 'github',
  type: 'code-check',
  description: 'Run AI-powered code quality analysis on push to main branches',
  outputPath: '.github/workflows/ai-code-check.yml',
  content: `# AI-Powered Code Quality Check
# This workflow analyzes code quality using Alexi
#
# Setup:
# 1. Add SAP AI Core credentials as repository secrets:
#    - SAP_AICORE_SERVICE_KEY: Your SAP AI Core service key JSON
#    OR for proxy mode:
#    - SAP_PROXY_BASE_URL: URL to your SAP proxy server
#
# 2. Optionally customize the analysis scope in the workflow

name: AI Code Check

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  ai-code-check:
    name: AI Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Alexi
        run: npm install -g alexi
      
      - name: Analyze Changed Files
        id: changed
        run: |
          # Get list of changed files in the last commit
          git diff --name-only HEAD~1 HEAD > changed_files.txt || echo "" > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
      
      - name: Run AI Code Analysis
        env:
          AICORE_SERVICE_KEY: \${{ secrets.SAP_AICORE_SERVICE_KEY }}
          SAP_PROXY_BASE_URL: \${{ secrets.SAP_PROXY_BASE_URL }}
          SAP_PROXY_API_KEY: \${{ secrets.SAP_PROXY_API_KEY }}
        run: |
          # Create analysis prompt
          cat << 'PROMPT' > analysis_prompt.txt
          Analyze the following code files for quality issues.
          
          Check for:
          1. Code style and consistency
          2. Potential bugs or logic errors
          3. Security vulnerabilities
          4. Performance issues
          5. Missing error handling
          6. Code complexity
          
          Provide a summary with actionable recommendations.
          Format output as markdown.
          
          Changed files:
          PROMPT
          
          cat changed_files.txt >> analysis_prompt.txt
          echo "" >> analysis_prompt.txt
          echo "File contents:" >> analysis_prompt.txt
          
          # Append content of changed files (limit to reasonable size)
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "--- $file ---" >> analysis_prompt.txt
              head -500 "$file" >> analysis_prompt.txt
              echo "" >> analysis_prompt.txt
            fi
          done < changed_files.txt
          
          # Run analysis
          alexi --prompt "$(cat analysis_prompt.txt)" --non-interactive
      
      - name: Upload Analysis Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-code-analysis
          path: |
            analysis_prompt.txt
            changed_files.txt
          retention-days: 7
`,
};

/**
 * GitHub Actions - Feature Implementation Template
 * Manual workflow to implement features using AI
 */
const githubFeatureImplementTemplate: CITemplate = {
  id: 'github-feature-implement',
  name: 'GitHub Actions - Feature Implement',
  platform: 'github',
  type: 'feature-implement',
  description: 'Manually trigger AI to implement a feature and create a PR',
  outputPath: '.github/workflows/ai-feature.yml',
  content: `# AI-Powered Feature Implementation
# This workflow uses Alexi to implement features
#
# Setup:
# 1. Add SAP AI Core credentials as repository secrets
# 2. Ensure workflow has write permissions for contents and pull-requests
#
# Usage:
# 1. Go to Actions > AI Feature Implementation
# 2. Click "Run workflow"
# 3. Enter feature description and optional branch name
# 4. The AI will create a branch, implement the feature, and open a PR

name: AI Feature Implementation

on:
  workflow_dispatch:
    inputs:
      feature_description:
        description: 'Description of the feature to implement'
        required: true
        type: string
      branch_name:
        description: 'Branch name for the feature (optional, auto-generated if empty)'
        required: false
        type: string
      base_branch:
        description: 'Base branch to create PR against'
        required: false
        default: 'main'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  implement-feature:
    name: Implement Feature with AI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Alexi
        run: npm install -g alexi
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Generate Branch Name
        id: branch
        run: |
          if [ -n "\${{ github.event.inputs.branch_name }}" ]; then
            BRANCH="\${{ github.event.inputs.branch_name }}"
          else
            # Generate branch name from feature description
            BRANCH="feature/ai-$(echo '\${{ github.event.inputs.feature_description }}' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | cut -c1-50)-\${{ github.run_id }}"
          fi
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
          echo "Using branch: $BRANCH"
      
      - name: Create Feature Branch
        run: |
          git checkout -b \${{ steps.branch.outputs.branch_name }}
      
      - name: Implement Feature with AI
        env:
          AICORE_SERVICE_KEY: \${{ secrets.SAP_AICORE_SERVICE_KEY }}
          SAP_PROXY_BASE_URL: \${{ secrets.SAP_PROXY_BASE_URL }}
          SAP_PROXY_API_KEY: \${{ secrets.SAP_PROXY_API_KEY }}
        run: |
          # Create implementation prompt
          cat << 'PROMPT' > implement_prompt.txt
          Implement the following feature in this codebase:
          
          Feature Description:
          \${{ github.event.inputs.feature_description }}
          
          Instructions:
          1. Analyze the existing codebase structure
          2. Implement the feature following existing patterns and conventions
          3. Add appropriate tests if test files exist in the project
          4. Update relevant documentation if needed
          5. Ensure the implementation is complete and functional
          
          Focus on clean, maintainable code that integrates well with the existing codebase.
          PROMPT
          
          # Run alexi to implement the feature
          alexi --prompt "$(cat implement_prompt.txt)" --allow-edits --non-interactive
      
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit Changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "feat: \${{ github.event.inputs.feature_description }}
          
          Implemented by AI using Alexi
          
          Triggered by: @\${{ github.actor }}
          Workflow run: \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}"
      
      - name: Push Branch
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git push origin \${{ steps.branch.outputs.branch_name }}
      
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \\
            --title "feat: \${{ github.event.inputs.feature_description }}" \\
            --body "## Summary
          
          This PR implements the following feature using AI:
          
          > \${{ github.event.inputs.feature_description }}
          
          ## Implementation Notes
          
          - Implemented by Alexi
          - Triggered by @\${{ github.actor }}
          - Please review the changes carefully before merging
          
          ## Checklist
          
          - [ ] Code review completed
          - [ ] Tests pass
          - [ ] Documentation updated (if applicable)
          
          ---
          *This PR was auto-generated by the AI Feature Implementation workflow*" \\
            --base \${{ github.event.inputs.base_branch }} \\
            --head \${{ steps.branch.outputs.branch_name }}
      
      - name: Report No Changes
        if: steps.changes.outputs.has_changes == 'false'
        run: |
          echo "::warning::No changes were made by the AI. The feature may already exist or the description was unclear."
`,
};

// ============ GitLab CI Templates ============

/**
 * GitLab CI - PR Review Template
 * Triggers on merge request events
 */
const gitlabPrReviewTemplate: CITemplate = {
  id: 'gitlab-pr-review',
  name: 'GitLab CI - MR Review',
  platform: 'gitlab',
  type: 'pr-review',
  description: 'Automatically review merge requests using SAP AI Core and post feedback as comments',
  outputPath: '.gitlab-ci-ai-review.yml',
  content: `# AI-Powered Merge Request Review for GitLab CI
# This pipeline uses Alexi to review merge requests
#
# Setup:
# 1. Add SAP AI Core credentials as CI/CD variables:
#    - SAP_AICORE_SERVICE_KEY: Your SAP AI Core service key JSON
#    OR for proxy mode:
#    - SAP_PROXY_BASE_URL: URL to your SAP proxy server
#    - SAP_PROXY_API_KEY: API key for proxy authentication (if required)
#
# 2. Add this file's content to your .gitlab-ci.yml or include it:
#    include:
#      - local: '.gitlab-ci-ai-review.yml'
#
# 3. Ensure the pipeline has API access for posting comments:
#    - Set GITLAB_TOKEN variable with a token that has api scope

stages:
  - review

ai-mr-review:
  stage: review
  image: node:22
  
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  
  variables:
    GIT_DEPTH: 0
  
  before_script:
    - npm install -g alexi
    - apt-get update && apt-get install -y curl
  
  script:
    # Get the diff between source and target branch
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...HEAD > mr_diff.txt
    
    # Create review prompt
    - |
      cat << 'PROMPT' > review_prompt.txt
      Review the following code changes from a merge request.
      
      Provide feedback on:
      1. Code quality and best practices
      2. Potential bugs or issues
      3. Security concerns
      4. Performance implications
      5. Suggestions for improvement
      
      Be constructive and specific. Reference line numbers when applicable.
      Format your response in markdown.
      
      MR Title: $CI_MERGE_REQUEST_TITLE
      Source Branch: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      Target Branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      
      Code Changes:
      PROMPT
    
    - cat mr_diff.txt >> review_prompt.txt
    
    # Run AI review
    - alexi --prompt "$(cat review_prompt.txt)" --output review_output.md --non-interactive || true
    
    # Post review as MR comment
    - |
      if [ -f review_output.md ] && [ -n "$GITLAB_TOKEN" ]; then
        # Escape content for JSON
        REVIEW_BODY=$(cat review_output.md | jq -Rs '.')
        curl --request POST \\
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \\
          --header "Content-Type: application/json" \\
          --data '{"body": '"$REVIEW_BODY"'}' \\
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
        echo "Review posted to merge request"
      else
        echo "Review output:"
        cat review_output.md || echo "No review generated"
      fi
  
  artifacts:
    paths:
      - review_output.md
      - mr_diff.txt
    expire_in: 7 days
    when: always
`,
};

/**
 * GitLab CI - Code Check Template
 * Code quality analysis on pipeline triggers
 */
const gitlabCodeCheckTemplate: CITemplate = {
  id: 'gitlab-code-check',
  name: 'GitLab CI - Code Check',
  platform: 'gitlab',
  type: 'code-check',
  description: 'Run AI-powered code quality analysis on pipeline triggers',
  outputPath: '.gitlab-ci-ai-check.yml',
  content: `# AI-Powered Code Quality Check for GitLab CI
# This pipeline analyzes code quality using Alexi
#
# Setup:
# 1. Add SAP AI Core credentials as CI/CD variables:
#    - SAP_AICORE_SERVICE_KEY: Your SAP AI Core service key JSON
#    OR for proxy mode:
#    - SAP_PROXY_BASE_URL: URL to your SAP proxy server
#
# 2. Add this file's content to your .gitlab-ci.yml or include it:
#    include:
#      - local: '.gitlab-ci-ai-check.yml'

stages:
  - analyze

ai-code-check:
  stage: analyze
  image: node:22
  
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
  
  variables:
    GIT_DEPTH: 10
  
  before_script:
    - npm install -g alexi
  
  script:
    # Get list of changed files
    - git diff --name-only HEAD~1 HEAD > changed_files.txt || echo "" > changed_files.txt
    - echo "Changed files:"
    - cat changed_files.txt
    
    # Create analysis prompt
    - |
      cat << 'PROMPT' > analysis_prompt.txt
      Analyze the following code files for quality issues.
      
      Check for:
      1. Code style and consistency
      2. Potential bugs or logic errors
      3. Security vulnerabilities
      4. Performance issues
      5. Missing error handling
      6. Code complexity
      
      Provide a summary with actionable recommendations.
      Format output as markdown.
      
      Project: $CI_PROJECT_NAME
      Branch: $CI_COMMIT_BRANCH
      Commit: $CI_COMMIT_SHA
      
      Changed files:
      PROMPT
    
    - cat changed_files.txt >> analysis_prompt.txt
    - echo "" >> analysis_prompt.txt
    - echo "File contents:" >> analysis_prompt.txt
    
    # Append content of changed files
    - |
      while IFS= read -r file; do
        if [ -f "$file" ]; then
          echo "--- $file ---" >> analysis_prompt.txt
          head -500 "$file" >> analysis_prompt.txt
          echo "" >> analysis_prompt.txt
        fi
      done < changed_files.txt
    
    # Run analysis
    - alexi --prompt "$(cat analysis_prompt.txt)" --output analysis_report.md --non-interactive
    
    - echo "=== Analysis Report ==="
    - cat analysis_report.md || echo "No report generated"
  
  artifacts:
    paths:
      - analysis_report.md
      - analysis_prompt.txt
      - changed_files.txt
    expire_in: 30 days
    when: always
    reports:
      dotenv: analysis_report.md
`,
};

// ============ All Templates Export ============

/**
 * All available CI/CD templates
 */
export const ALL_TEMPLATES: CITemplate[] = [
  githubPrReviewTemplate,
  githubCodeCheckTemplate,
  githubFeatureImplementTemplate,
  gitlabPrReviewTemplate,
  gitlabCodeCheckTemplate,
];

/**
 * Get templates by platform
 */
export function getTemplatesByPlatform(platform: CIPlatform): CITemplate[] {
  return ALL_TEMPLATES.filter(t => t.platform === platform);
}

/**
 * Get templates by type
 */
export function getTemplatesByType(type: TemplateType): CITemplate[] {
  return ALL_TEMPLATES.filter(t => t.type === type);
}

/**
 * Get a specific template
 */
export function getTemplate(platform: CIPlatform, type: TemplateType): CITemplate | undefined {
  return ALL_TEMPLATES.find(t => t.platform === platform && t.type === type);
}
